name: Build SDF Reader

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'src/SdfReader/**'
  workflow_dispatch:

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write  # Allow writing to repository contents
  actions: read    # Allow reading workflow files

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore src/SdfReader/packages.config -PackagesDirectory src/packages

    - name: Build SDF Reader
      run: msbuild src/SdfReader/SdfReader.csproj /p:Configuration=Release

    - name: Create output directory
      run: |
        if (!(Test-Path "src/SdfReader/bin/Debug")) {
          New-Item -ItemType Directory -Path "src/SdfReader/bin/Debug" -Force
        }

    - name: Copy executable to expected location
      run: |
        Copy-Item "src/SdfReader/bin/Release/SdfReader.exe" "src/SdfReader/bin/Debug/SdfReader.exe" -Force

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push if changed
      run: |
        git add -f src/SdfReader/bin/Debug/SdfReader.exe
        git diff --staged --quiet || (git commit -m "Auto-build: Update SdfReader.exe" && git push)