name: Build SDF Reader

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'SdfReader/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore SdfReader/SdfReader.sln

    - name: Build SDF Reader
      run: msbuild SdfReader/SdfReader.sln /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath=bin\Release\ /verbosity:minimal

    - name: Create output directory
      run: |
        if (!(Test-Path "SdfReader/bin/Debug")) {
          New-Item -ItemType Directory -Path "SdfReader/bin/Debug" -Force
        }

    - name: Copy executable to expected location
      run: |
        Copy-Item "SdfReader/bin/Release/SdfReader.exe" "SdfReader/bin/Debug/SdfReader.exe" -Force

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push if changed
      run: |
        git add SdfReader/bin/Debug/SdfReader.exe
        git diff --staged --quiet || (git commit -m "Auto-build: Update SdfReader.exe" && git push)